---
title: "Untitled"
author: "Javier Lobato Menendez"
date: "2024-09-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
formula <- function(x){
 x^2
}
print(formula)
formula(c(-10:10))
plot(formula(c(-10:10)))

#queda mas claro si hago esto: 
#x_values <- -10:10
#y_values <- formula(x_values)
#plot (x_values, y_values)
```
El minimo es x =0
```{r}
optimize(formula,c(-10:10), maximum = FALSE) #El minimum es el minimo
```

```{r}
trigo <- function(x) {
  h <- sin(x*pi/180)  # Calculate the sine of x
  return(h)    # Return the result of the sine function
}

result <- trigo(2*pi/2)  
print(result) 

plot(trigo(c(0: 2*pi)))
```
#ejercicios intermedios
```{r}
rad <- function(x){
  num <- sin(x*pi/180)
  return (num)
}
print(rad)

rad(180)

plot(rad(c(0:360)))
```
```{r}
optimize(rad, c(0:180, lower=min(0), upper = max(180), maximum = TRUE ))
```

```{r}
summary(mtcars)
```
```{r}
plot(mpg~wt, data =mtcars)
modelo <- lm(mpg~wt, data = mtcars)
summary(modelo)
```
```{r}
#lm(mtcars$mpg ~ mtcars[, i]) cada columna = variable
#lapply(1:ncol(mtcars), function(i) {...}) funcion a cada columna

lista <- lapply(1:ncol(mtcars), function(i) {
         regre <- lm(mtcars$mpg ~ mtcars[, i])})
lista
```

```{r}
vecino <- function(p, n=length(p)) {
  ij <- sample(n,2)
  p[ij] <- p[rev(ij)]
  p
}

# Function to count collisions
colisiones <- function(p, n=length(p)) {
  con <- 0
  for(i in 1:(n-1)) {
    for(j in (i+1):n) {
      if(abs(p[i] - p[j]) == abs(i - j)) {
        con <- con + 1
      }
    }
  }
  return(con)
}

# Optimize using simulated annealing
sol_1 <- optim(sample(8), colisiones, gr = vecino, method = "SANN") #añadir control = list(maxit = 10000))
sol_sann <- optim(sample(8), colisiones, gr = vecino, method = "SANN", control = list(maxit = 10000))

sol_2 <- optim(sample(8), colisiones, gr = vecino, method = "Nelder-Mead")

```
La mejores el metodo SANN porque tiene 10000 repeticiones y tiene 0 choques.

Warning in optim(c(5), function(x) { :
  one-dimensional optimization by Nelder-Mead is unreliable:
use "Brent" or optimize() directly

Optimize -> 1 variable
Optim -> 2 variables o mas
```{r}
optim(5, function(x){(x[1]-3)^2 + 5}, method = "Nelder-Mead")
```

```{r}
library(parallel)
pausa <- function() Sys.sleep(1)
system.time(parallel::mclapply(1:2, pausa))
```






















